trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'demo-function-yaml-cicd - Build'
  
variables:
  vmImageName: 'vs2017-win2016'
  azureSubscription: '{{ azureRmConnection.Id }}'

stages:
- template: azure-release-pipelines-stage-template.yml
  parameters:
    stageName: 'API-CI'
    azureSubscription: ${azureSubscription}
    functionAppName: 'demo-function-api-ci'
    resourceGroupName: 'demo-function-api-ci'
    storageAccountName: 'azfunctionsdapici'
    region: 'Central US'
