trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'demo-function-yaml-cicd - Build'
  
variables:
  vmImageName: 'vs2017-win2016'
  azureSubscription: 'Internal Demo Account (164a84cf-b099-4567-a527-c2a8143a32c7)'

stages:
 - stage: CI
   displayName: CI stage 
   jobs:
    - template: azure-release-pipelines-stage-template.yml
      parameters:
        functionAppName: 'demo-function-api-ci'
        resourceGroupName: 'demo-function-api-ci'
        storageAccountName: 'azfunctionsdapici'
        region: 'Central US'
